In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression
import os

In [3]:
# Cargamos los csv de los tifs
path = "saved_files/dataset"
dfs = {}
for archivo in os.listdir(path):
    if archivo.endswith("_features.csv"):
        nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
        ruta_completa = os.path.join(path, archivo)
        dfs[nombre_sin_extension[:-9]] = pd.read_csv(ruta_completa)

In [4]:
dfs_to_keep = [

]

In [5]:
dfs = {k: dfs[k] for k in dfs_to_keep if k in dfs}

for nombre_df, df in dfs.items():
    for band_set in ["rhow", "rhown"]:
        dfs[nombre_df] = df.dropna()

In [7]:
dfs["c2x-complex-nets_1x1_upct_depth_gt_1"]

,Date,Buoy,Latitude,Longitude,rhow_B1,rhow_B2,rhow_B3,rhow_B4,rhow_B5,rhow_B6,...,dif_rel_4bands_rhown_B2_B5_B3_B4,dif_rel_4bands_rhown_B2_B5_B4_B3,dif_rel_4bands_rhown_B3_B2_B4_B5,dif_rel_4bands_rhown_B3_B2_B5_B4,dif_rel_4bands_rhown_B3_B4_B5_B2,dif_rel_4bands_rhown_B3_B5_B4_B2,dif_rel_4bands_rhown_B4_B2_B5_B3,dif_rel_4bands_rhown_B4_B3_B5_B2,sum_norm_3bands_rhown_B2_B4_B3,sum_norm_3bands_rhown_B3_B5_B4
0,2017-06-30,CTD1,4187246,695025,0.023568,0.034184,0.043664,0.014988,0.009146,0.002320,...,0.672,3.168,-0.300,0.638,2.563,4.033,0.224,0.067,0.637,0.905
1,2017-06-30,CTD2,4181518,693105,0.013951,0.022364,0.026365,0.006800,0.003868,0.001000,...,1.498,4.968,-0.469,0.560,3.546,5.812,0.150,0.077,0.605,0.918
2,2017-06-30,CTD3,4181698,695238,0.017592,0.024643,0.031816,0.010574,0.007355,0.001946,...,0.333,2.978,-0.144,0.595,2.679,3.846,0.200,0.034,0.626,0.924
3,2017-06-30,CTD4,4180266,698264,0.016405,0.024627,0.035083,0.012218,0.008422,0.002163,...,0.053,2.534,-0.027,0.735,2.487,3.608,0.259,0.007,0.620,0.919
4,2017-06-30,CTD6,4176009,695829,0.027602,0.037375,0.045626,0.021838,0.013271,0.003668,...,0.507,2.111,-0.292,0.531,1.698,2.534,0.255,0.094,0.716,0.893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2023-05-25,CTD7,4176724,690397,0.020669,0.032768,0.041319,0.006504,0.004481,0.000994,...,1.321,7.337,-0.277,0.661,6.045,9.514,0.107,0.029,0.527,0.949
376,2023-05-25,CTD8,4174178,693048,0.021099,0.032493,0.039426,0.008228,0.005300,0.001231,...,1.388,5.797,-0.372,0.618,4.459,7.181,0.134,0.050,0.566,0.933
377,2023-05-25,CTD10,4170388,695646,0.012523,0.019127,0.025498,0.006645,0.004663,0.001132,...,0.374,3.825,-0.135,0.668,3.476,5.141,0.179,0.025,0.581,0.931
378,2023-05-25,CTD11,4169609,700351,0.013461,0.019871,0.024722,0.006568,0.004507,0.001144,...,0.654,4.062,-0.222,0.568,3.449,5.070,0.154,0.041,0.596,0.932
379,2023-05-25,CTD12,4173438,695414,0.019546,0.029300,0.034308,0.008993,0.005474,0.001399,...,1.308,4.757,-0.414,0.547,3.519,5.595,0.147,0.070,0.605,0.921

In [11]:
dfs["c2x-complex-nets_1x1_imida_depth_gt_1"].merge(dfs["c2x-complex-nets_1x1_upct_depth_gt_1"], how="outer", on=["Date","Buoy"])

,Date,Buoy,Latitude_x,Longitude_x,rhow_B1_x,rhow_B2_x,rhow_B3_x,rhow_B4_x,rhow_B5_x,rhow_B6_x,...,dif_rel_4bands_rhown_B2_B5_B3_B4_y,dif_rel_4bands_rhown_B2_B5_B4_B3_y,dif_rel_4bands_rhown_B3_B2_B4_B5_y,dif_rel_4bands_rhown_B3_B2_B5_B4_y,dif_rel_4bands_rhown_B3_B4_B5_B2_y,dif_rel_4bands_rhown_B3_B5_B4_B2_y,dif_rel_4bands_rhown_B4_B2_B5_B3_y,dif_rel_4bands_rhown_B4_B3_B5_B2_y,sum_norm_3bands_rhown_B2_B4_B3_y,sum_norm_3bands_rhown_B3_B5_B4_y
0,2016-08-09,CTD1,4187246.0,695025.0,0.011593,0.016915,0.028795,0.014279,0.013503,0.003823,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2016-08-09,CTD2,4181518.0,693105.0,0.011363,0.014885,0.021044,0.012019,0.009860,0.003023,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2016-08-09,CTD3,4181698.0,695238.0,0.013396,0.017670,0.024609,0.014144,0.011111,0.003436,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2016-08-09,CTD4,4180266.0,698264.0,0.006875,0.008679,0.015606,0.007680,0.015444,0.003673,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2016-08-09,CTD6,4176009.0,695829.0,0.011116,0.015488,0.022424,0.011246,0.008419,0.002437,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,2021-11-26,CTD7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.243,1.740,0.151,0.747,1.936,2.597,0.311,-0.047,0.651,0.925
404,2021-11-26,CTD8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.018,6.218,-0.004,0.734,6.201,8.897,0.115,0.000,0.504,0.959
405,2021-11-26,CTD10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.600,5.568,-0.155,0.661,4.988,7.423,0.128,0.020,0.539,0.947
406,2021-11-26,CTD11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.574,6.770,-0.119,0.628,6.209,8.951,0.099,0.013,0.520,0.958
407,2021-11-26,CTD12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.365,3.388,0.136,0.757,3.729,5.062,0.189,-0.025,0.551,0.947

In [ ]:
# Todas
dates = [
    '2016-08-09', '2016-09-08', '2017-06-30', '2018-02-20', '2018-03-07', 
    '2018-05-16', '2018-06-20', '2018-07-10', '2018-08-29', '2018-10-03', #'2019-09-18',
    '2018-11-07', '2019-03-12', '2019-06-25', '2019-07-10', '2019-07-30', 
    '2019-08-14', '2019-09-28', '2019-10-03', '2019-11-27', '2020-02-20', 
    '2020-03-11', '2020-12-21', '2021-01-05', '2021-04-20', '2021-05-20',
    '2021-06-14', '2021-08-13', '2021-11-11', '2021-11-26', '2021-12-01', 
    '2022-02-24', '2022-07-14', '2022-07-29', '2022-08-03', '2022-09-07', 
    '2022-09-27', '2023-01-10', '2023-03-01', '2023-03-16', '2023-04-20', 
    '2023-05-25'
]

filter_dates = pd.to_datetime(dates, format= "%Y-%m-%d")

for nombre_df, df in dfs.items():
    df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d", errors='coerce')  # asegurarse
    dfs[nombre_df] = df[df["Date"].isin(filter_dates)].copy()