In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.linear_model import LinearRegression
import os

In [75]:
# Cargamos los csv de los tifs
path = "saved_files/dataset"
dfs = {}
for archivo in os.listdir(path):
    if archivo.endswith("_features.csv"):
        nombre_sin_extension = os.path.splitext(archivo)[0]  # sin .csv
        ruta_completa = os.path.join(path, archivo)
        dfs[nombre_sin_extension] = pd.read_csv(ruta_completa)

In [76]:
dfs["c2x-complex-nets_1x1_imida_depth_gt_1_features"].head(2)

,Date,Buoy,Latitude,Longitude,rhow_B1,rhow_B2,rhow_B3,rhow_B4,rhow_B5,rhow_B6,...,dif_rel_4bands_rhown_B3_B4_B5_B1,dif_rel_4bands_rhown_B3_B4_B5_B2,dif_rel_4bands_rhown_B3_B5_B4_B1,dif_rel_4bands_rhown_B3_B5_B4_B2,dif_rel_4bands_rhown_B4_B1_B5_B2,dif_rel_4bands_rhown_B4_B1_B5_B3,dif_rel_4bands_rhown_B4_B2_B5_B1,dif_rel_4bands_rhown_B4_B2_B5_B3,dif_rel_4bands_rhown_B4_B3_B5_B1,dif_rel_4bands_rhown_B4_B3_B5_B2
0,2017-06-30,CTD1,4187246,695025,0.023568,0.034184,0.043664,0.014988,0.009146,0.00232,...,2.434,2.563,3.829,4.033,0.367,0.428,0.033,0.224,-0.063,0.067
1,2017-06-30,CTD2,4181518,693105,0.013951,0.022364,0.026365,0.006800,0.003868,0.00100,...,3.431,3.546,5.623,5.812,0.311,0.339,0.006,0.150,-0.039,0.077

Las fórmulas que queremos comprobar son:

- $y_1 = 0.6386 e^{4.7513x}$, donde $y$ es la clorofila y $x$ es la relación de $(Green - Blue)/(Green + Blue)$

- $y_2 = 124.94x - 115.35$ donde $x = \frac{Green+NIR1}{Green + Red}$

- $y_3 = 22.835x - 12.974$ donde $x = \frac{NIR1 - NIR2}{Red - NIR2}$

- $y_4 = 32.448x - 21.408$ donde $x = \frac{NIR1}{Red}$


con las fechas


dates = [
    "28/10/2016", "20/06/2018", "07/11/2018", "14/08/2019",
    "30/06/2017", "10/07/2018", "12/03/2019", "18/09/2019",
    "20/02/2018", "29/08/2018", "25/06/2019", "03/10/2019",
    "07/03/2018", "03/10/2018"
]

Filtramos los dataframes para dejar solamente esas fechas:

In [77]:
dates = [
    "28/10/2016", "20/06/2018", "07/11/2018", "14/08/2019",
    "30/06/2017", "10/07/2018", "12/03/2019", "18/09/2019",
    "20/02/2018", "29/08/2018", "25/06/2019", "03/10/2019",
    "07/03/2018", "03/10/2018"
]
filter_dates = pd.to_datetime(dates, format="%d/%m/%Y")

for nombre_df, df in dfs.items():
    df["Date"] = pd.to_datetime(df["Date"], format="%Y-%m-%d", errors='coerce')  # asegurarse
    dfs[nombre_df] = df[df["Date"].isin(filter_dates)].copy()

Recordemos que en el paper quitan las observaciones cuya medida de Chl-a esté fuera de la mediana $\pm$ una desviación estándar. Para ello hacemos lo siguiente (no lo hacemos porque los resultados empeoran muchísimo.). De hacerlo, pasaríamos de tener 130 filas, a quedarnos solamente con 107.

In [69]:
# for nombre_df, df in dfs.items():
#     if "Chl" in df.columns:
#         mediana = df["Chl"].median()
#         desviacion = df["Chl"].std()
#         umbral_sup = mediana + desviacion
#         umbral_inf = mediana - desviacion

#         # Filtrar
#         df_filtrado = df[(df["Chl"] >= umbral_inf) & (df["Chl"] <= umbral_sup)].copy()
#         dfs[nombre_df] = df_filtrado

Definimos funciones para las fórmulas que queremos aplicar.
Recordar que:
- Blue = rhow_B2
- Green = rhow_B3
- Red = rhow_B4
- NIR1 = rhow_B5
- NIR2 = rhow_B6

In [78]:
def add_y(blue, green, red, nir1, nir2):
    x_1 = (green-blue)/(green+blue)
    y_1 = 0.6386*np.exp(4.7513*x_1)

    x_2 = (green+nir1)/(green+red)
    y_2 = 124.94*x_2 - 115.35

    x_3 = (nir1-nir2)/(red-nir2)
    y_3 = 22.835*x_3 - 12.974

    x_4 = nir1/red
    y_4 = 32.448*x_4 - 21.408

    return y_1, y_2, y_3, y_4

In [79]:
def add_y_columns_to_df(df, band_set="rhow"):
    # Mapas de bandas
    mapping = band_maps[band_set]

    # Extraer bandas desde el DataFrame
    blue = df[mapping["Blue"]]
    green = df[mapping["Green"]]
    red = df[mapping["Red"]]
    nir1 = df[mapping["NIR1"]]
    nir2 = df[mapping["NIR2"]]

    # Aplicar fórmula
    y_1, y_2, y_3, y_4 = add_y(blue, green, red, nir1, nir2)

    # Añadir columnas al DataFrame
    if band_set == "rhow":
        df["y_1_rhow"] = y_1
        df["y_2_rhow"] = y_2
        df["y_3_rhow"] = y_3
        df["y_4_rhow"] = y_4

    elif band_set == "rhown":
        df["y_1_rhown"] = y_1
        df["y_2_rhown"] = y_2
        df["y_3_rhown"] = y_3
        df["y_4_rhown"] = y_4

    return df

band_maps = {
    "rhow": {
        "Blue": "rhow_B2",
        "Green": "rhow_B3",
        "Red": "rhow_B4",
        "NIR1": "rhow_B5",
        "NIR2": "rhow_B6"
    },
    "rhown": {
        "Blue": "rhown_B2",
        "Green": "rhown_B3",
        "Red": "rhown_B4",
        "NIR1": "rhown_B5",
        "NIR2": "rhown_B6"
    }
}

In [80]:
for nombre_df, df in dfs.items():
    # De momento solo con rhow
    for band_set in ["rhow", "rhown"]:
        dfs[nombre_df] = add_y_columns_to_df(df, band_set)

In [111]:
metrics_df = pd.DataFrame()
for nombre_df, df in dfs.items():

    #R2
    # try:
    #     metrics_df.loc[nombre_df[:-9], "r2_y_1_rhow"] = r2_score(df["Chl"], df["y_1_rhow"]).round(3)
    #     metrics_df.loc[nombre_df[:-9], "r2_y_2_rhow"] = r2_score(df["Chl"], df["y_2_rhow"]).round(3)
    #     metrics_df.loc[nombre_df[:-9], "r2_y_3_rhow"] = r2_score(df["Chl"], df["y_3_rhow"]).round(3)
    #     metrics_df.loc[nombre_df[:-9], "r2_y_4_rhow"] = r2_score(df["Chl"], df["y_4_rhow"]).round(3)
    # except:
    #     continue

    # try:
    #     metrics_df.loc[nombre_df[:-9], "r2_y_1_rhown"] = r2_score(df["Chl"], df["y_1_rhown"]).round(3)
    #     metrics_df.loc[nombre_df[:-9], "r2_y_2_rhown"] = r2_score(df["Chl"], df["y_2_rhown"]).round(3)
    #     metrics_df.loc[nombre_df[:-9], "r2_y_3_rhown"] = r2_score(df["Chl"], df["y_3_rhown"]).round(3)
    #     metrics_df.loc[nombre_df[:-9], "r2_y_4_rhown"] = r2_score(df["Chl"], df["y_4_rhown"]).round(3)
    # except:
    #     continue

    # RMSE
    try:
        metrics_df.loc[nombre_df[:-9], "rmse_y_1_rhow"] = np.sqrt(mean_squared_error(df["Chl"], df["y_1_rhow"])).round(3)
        metrics_df.loc[nombre_df[:-9], "rmse_y_2_rhow"] = np.sqrt(mean_squared_error(df["Chl"], df["y_2_rhow"])).round(3)
        metrics_df.loc[nombre_df[:-9], "rmse_y_3_rhow"] = np.sqrt(mean_squared_error(df["Chl"], df["y_3_rhow"])).round(3)
        metrics_df.loc[nombre_df[:-9], "rmse_y_4_rhow"] = np.sqrt(mean_squared_error(df["Chl"], df["y_4_rhow"])).round(3)
    except:
        continue

    try:
        metrics_df.loc[nombre_df[:-9], "rmse_y_1_rhown"] = np.sqrt(mean_squared_error(df["Chl"], df["y_1_rhown"])).round(3)
        metrics_df.loc[nombre_df[:-9], "rmse_y_2_rhown"] = np.sqrt(mean_squared_error(df["Chl"], df["y_2_rhown"])).round(3)
        metrics_df.loc[nombre_df[:-9], "rmse_y_3_rhown"] = np.sqrt(mean_squared_error(df["Chl"], df["y_3_rhown"])).round(3)
        metrics_df.loc[nombre_df[:-9], "rmse_y_4_rhown"] = np.sqrt(mean_squared_error(df["Chl"], df["y_4_rhown"])).round(3)
    except:
        continue

    #NRMSE
    try:
        metrics_df.loc[nombre_df[:-9], "nrmse_y_1_rhow"] = (metrics_df.loc[nombre_df[:-9], "rmse_y_1_rhow"]/(df["Chl"].max()-df["Chl"].min())).round(3)*100
        metrics_df.loc[nombre_df[:-9], "nrmse_y_2_rhow"] = (metrics_df.loc[nombre_df[:-9], "rmse_y_2_rhow"]/(df["Chl"].max()-df["Chl"].min())).round(3)*100
        metrics_df.loc[nombre_df[:-9], "nrmse_y_3_rhow"] = (metrics_df.loc[nombre_df[:-9], "rmse_y_3_rhow"]/(df["Chl"].max()-df["Chl"].min())).round(3)*100
        metrics_df.loc[nombre_df[:-9], "nrmse_y_4_rhow"] = (metrics_df.loc[nombre_df[:-9], "rmse_y_4_rhow"]/(df["Chl"].max()-df["Chl"].min())).round(3)*100
    except:
        continue

In [114]:
metrics_df[metrics_df.lt(2.5).any(axis=1)]

,rmse_y_1_rhow,rmse_y_2_rhow,rmse_y_3_rhow,rmse_y_4_rhow,rmse_y_1_rhown,rmse_y_2_rhown,rmse_y_3_rhown,rmse_y_4_rhown,nrmse_y_1_rhow,nrmse_y_2_rhow,nrmse_y_3_rhow,nrmse_y_4_rhow
c2x-nets_1x1_upct_depth_lt_1,3.766,3.015,2.658,2.967,3.611,2.673,2.424,2.566,20.8,16.6,14.7,16.4
c2x-nets_9x9_upct_depth_lt_2,4.260,2.758,2.431,2.683,4.149,3.053,2.782,2.768,19.5,12.6,11.1,12.3
c2x-nets_5x5_imida_depth_gt_1,2.624,4.289,3.816,4.011,2.553,2.850,2.498,2.727,18.1,29.6,26.4,27.7
c2x-nets_5x5_upct_depth_lt_2,4.226,2.717,2.332,2.638,4.091,2.946,2.652,2.647,19.3,12.4,10.7,12.1
c2x-complex-nets_5x5_upct_depth_lt_1,4.000,7.114,6.493,6.121,3.940,3.081,2.384,2.403,22.1,39.3,35.8,33.8
c2x-nets_9x9_imida_depth_gt_1,2.550,4.265,3.808,3.995,2.489,2.863,2.543,2.769,17.6,29.5,26.3,27.6
c2x-nets_5x5_upct_depth_gt_1,3.178,3.564,3.096,3.352,3.073,2.697,2.322,2.474,15.3,17.1,14.9,16.1
c2x-complex-nets_3x3_upct_depth_lt_1,4.010,7.068,6.221,6.017,3.953,3.027,2.346,2.422,22.1,39.0,34.3,33.2
c2x-complex-nets_9x9_upct_depth_lt_1,3.986,7.113,7.082,6.328,3.913,3.044,2.497,2.518,22.0,39.3,39.1,34.9
c2x-nets_3x3_upct_depth_lt_2,4.244,2.843,2.421,2.743,4.106,2.932,2.581,2.637,19.4,13.0,11.1,12.5
c2x-complex-nets_3x3_upct_depth_gt_1,3.765,7.329,6.340,6.043,3.699,3.429,2.387,2.515,18.1,35.2,30.5,29.1
c2x-nets_3x3_upct_depth_gt_1,3.195,3.749,3.258,3.475,3.081,2.812,2.377,2.553,15.4,18.0,15.7,16.7
c2x-nets_3x3_upct_depth_lt_1,3.698,2.912,2.483,2.775,3.562,2.494,2.157,2.290,20.4,16.1,13.7,15.3
c2x-nets_9x9_upct_depth_lt_1,3.679,2.763,2.405,2.641,3.566,2.572,2.326,2.383,20.3,15.3,13.3,14.6
c2x-nets_5x5_upct_depth_lt_1,3.660,2.736,2.338,2.615,3.526,2.463,2.192,2.257,20.2,15.1,12.9,14.4
c2x-nets_9x9_upct_depth_gt_1,3.161,3.532,3.081,3.329,3.072,2.728,2.384,2.529,15.2,17.0,14.8,16.0

In [100]:
metrics_df[metrics_df.gt(0.65).any(axis=1)]

,r2_y_1_rhow,r2_y_2_rhow,r2_y_3_rhow,r2_y_4_rhow,r2_y_1_rhown,r2_y_2_rhown,r2_y_3_rhown,r2_y_4_rhown,rmse_y_1_rhow,rmse_y_2_rhow,rmse_y_3_rhow,rmse_y_4_rhow,rmse_y_1_rhown,rmse_y_2_rhown,rmse_y_3_rhown,rmse_y_4_rhown
c2x-nets_1x1_imida_depth_lt_2,0.191,0.397,0.519,0.431,0.245,0.472,0.571,0.541,4.074,3.516,3.140,3.417,3.935,3.291,2.966,3.069
c2x-complex-nets_3x3_imida_depth_lt_2,-0.036,-1.343,-0.743,-0.600,-0.005,0.337,0.612,0.600,4.609,6.932,5.978,5.727,4.540,3.688,2.821,2.862
c2x-nets_1x1_upct_depth_lt_2,0.221,0.629,0.713,0.634,0.276,0.579,0.654,0.639,4.283,2.954,2.599,2.936,4.129,3.147,2.855,2.917
c2x-complex-nets_5x5_imida_depth_gt_1,-0.094,-6.114,-4.865,-4.082,-0.054,-0.565,0.157,0.056,3.132,7.988,7.253,6.752,3.075,3.746,2.749,2.910
c2x-nets_1x1_imida_depth_gt_1,0.222,-1.320,-0.899,-1.013,0.286,-0.061,0.164,0.014,2.642,4.562,4.127,4.250,2.531,3.084,2.738,2.975
c2x-complex-nets_3x3_imida_depth_lt_1,-0.026,-0.466,-0.087,-0.025,-0.002,0.407,0.591,0.597,5.624,6.720,5.786,5.620,5.556,4.275,3.548,3.523
c2x-nets_1x1_upct_depth_lt_1,0.198,0.486,0.600,0.502,0.262,0.596,0.668,0.627,3.766,3.015,2.658,2.967,3.611,2.673,2.424,2.566
c2x-complex-nets_3x3_upct_depth_lt_2,0.043,-0.972,-0.477,-0.380,0.069,0.478,0.681,0.680,4.746,6.815,5.897,5.701,4.682,3.505,2.739,2.743
c2x-nets_9x9_upct_depth_lt_2,0.229,0.677,0.749,0.694,0.269,0.604,0.671,0.674,4.260,2.758,2.431,2.683,4.149,3.053,2.782,2.768
c2x-complex-nets_1x1_upct_depth_gt_1,-0.035,-3.852,-2.982,-2.228,0.004,-0.097,0.533,0.495,3.756,8.133,7.367,6.633,3.685,3.867,2.524,2.624
c2x-nets_5x5_imida_depth_gt_1,0.232,-1.051,-0.623,-0.793,0.273,0.094,0.305,0.171,2.624,4.289,3.816,4.011,2.553,2.850,2.498,2.727
c2x-nets_5x5_upct_depth_lt_2,0.242,0.686,0.769,0.704,0.289,0.631,0.701,0.703,4.226,2.717,2.332,2.638,4.091,2.946,2.652,2.647
c2x-complex-nets_5x5_upct_depth_lt_1,0.095,-1.864,-1.386,-1.120,0.122,0.463,0.678,0.673,4.000,7.114,6.493,6.121,3.940,3.081,2.384,2.403
c2x-nets_5x5_imida_depth_lt_1,0.185,0.612,0.668,0.616,0.226,0.514,0.577,0.585,5.010,3.460,3.198,3.439,4.883,3.870,3.609,3.574
c2x-complex-nets_3x3_imida_depth_gt_1,-0.087,-5.804,-4.220,-3.728,-0.046,-0.439,0.261,0.138,3.122,7.812,6.842,6.512,3.063,3.593,2.574,2.780
c2x-nets_9x9_imida_depth_gt_1,0.275,-1.028,-0.617,-0.779,0.309,0.086,0.279,0.145,2.550,4.265,3.808,3.995,2.489,2.863,2.543,2.769
c2x-nets_5x5_upct_depth_gt_1,0.259,0.068,0.297,0.175,0.307,0.466,0.605,0.551,3.178,3.564,3.096,3.352,3.073,2.697,2.322,2.474
c2x-complex-nets_3x3_upct_depth_lt_1,0.090,-1.827,-1.190,-1.049,0.116,0.482,0.689,0.668,4.010,7.068,6.221,6.017,3.953,3.027,2.346,2.422
c2x-complex-nets_5x5_upct_depth_gt_1,-0.044,-3.076,-2.306,-1.855,-0.009,0.067,0.526,0.498,3.773,7.454,6.713,6.238,3.708,3.567,2.541,2.615
c2x-complex-nets_5x5_imida_depth_lt_2,-0.037,-1.411,-0.934,-0.685,-0.006,0.320,0.605,0.598,4.611,7.031,6.297,5.879,4.541,3.734,2.847,2.871
c2x-complex-nets_9x9_upct_depth_lt_2,0.051,-0.972,-0.934,-0.528,0.082,0.485,0.657,0.664,4.727,6.815,6.748,5.997,4.650,3.481,2.842,2.812
c2x-complex-nets_1x1_imida_depth_lt_2,-0.033,-1.928,-1.409,-0.949,-0.001,0.191,0.591,0.582,4.602,7.749,7.029,6.322,4.530,4.072,2.895,2.927
c2x-nets_1x1_imida_depth_lt_1,0.164,0.639,0.699,0.623,0.210,0.513,0.576,0.569,5.074,3.333,3.047,3.410,4.935,3.876,3.615,3.644
c2x-complex-nets_1x1_upct_depth_lt_2,0.048,-1.537,-1.127,-0.737,0.075,0.337,0.644,0.650,4.734,7.729,7.077,6.396,4.666,3.952,2.893,2.872
c2x-nets_3x3_imida_depth_lt_2,0.197,0.405,0.546,0.464,0.245,0.522,0.631,0.602,4.058,3.493,3.051,3.317,3.936,3.130,2.753,2.857
c2x-nets_9x9_imida_depth_lt_2,0.230,0.418,0.516,0.456,0.270,0.483,0.567,0.557,3.973,3.456,3.149,3.340,3.869,3.257,2.980,3.013
c2x-nets_1x1_upct_depth_gt_1,0.260,-0.132,0.098,0.008,0.323,0.322,0.481,0.416,3.176,3.928,3.507,3.678,3.038,3.040,2.659,2.822
c2x-complex-nets_9x9_upct_depth_lt_1,0.101,-1.862,-1.838,-1.265,0.134,0.476,0.647,0.641,3.986,7.113,7.082,6.328,3.913,3.044,2.497,2.518
c2x-complex-nets_9x9_imida_depth_lt_2,-0.029,-1.335,-1.228,-0.749,0.005,0.363,0.598,0.590,4.595,6.920,6.760,5.989,4.517,3.613,2.872,2.900
c2x-complex-nets_1x1_imida_depth_lt_1,-0.022,-0.855,-0.536,-0.260,0.003,0.313,0.578,0.587,5.613,7.561,6.879,6.230,5.541,4.601,3.605,3.569
c2x-nets_3x3_imida_depth_gt_1,0.234,-1.245,-0.778,-0.911,0.282,-0.009,0.247,0.106,2.621,4.487,3.994,4.140,2.537,3.009,2.599,2.832
c2x-nets_3x3_upct_depth_lt_2,0.235,0.657,0.751,0.680,0.284,0.635,0.717,0.705,4.244,2.843,2.421,2.743,4.106,2.932,2.581,2.637
c2x-complex-nets_5x5_upct_depth_lt_2,0.045,-1.002,-0.622,-0.433,0.071,0.464,0.676,0.684,4.742,6.865,6.179,5.810,4.677,3.552,2.763,2.728
c2x-complex-nets_3x3_upct_depth_gt_1,-0.040,-2.940,-1.949,-1.680,-0.004,0.137,0.582,0.536,3.765,7.329,6.340,6.043,3.699,3.429,2.387,2.515
c2x-nets_3x3_upct_depth_gt_1,0.251,-0.031,0.221,0.114,0.303,0.420,0.586,0.522,3.195,3.749,3.258,3.475,3.081,2.812,2.377,2.553
c2x-nets_3x3_upct_depth_lt_1,0.226,0.520,0.651,0.564,0.282,0.648,0.737,0.703,3.698,2.912,2.483,2.775,3.562,2.494,2.157,2.290
c2x-complex-nets_9x9_imida_depth_gt_1,-0.087,-5.975,-5.594,-4.247,-0.041,-0.492,0.108,0.015,3.122,7.910,7.691,6.860,3.056,3.659,2.829,2.973
c2x-nets_9x9_imida_depth_lt_1,0.190,0.598,0.638,0.602,0.224,0.488,0.547,0.560,4.996,3.519,3.338,3.501,4.889,3.970,3.736,3.683
c2x-nets_5x5_imida_depth_lt_2,0.203,0.423,0.541,0.464,0.249,0.506,0.599,0.584,4.042,3.441,3.070,3.317,3.924,3.183,2.868,2.919
c2x-complex-nets_1x1_upct_depth_lt_1,0.096,-2.624,-2.100,-1.559,0.123,0.279,0.628,0.616,3.998,8.003,7.402,6.725,3.938,3.570,2.565,2.603
c2x-complex-nets_1x1_imida_depth_gt_1,-0.081,-7.182,-5.752,-4.545,-0.036,-0.807,0.181,0.064,3.114,8.567,7.782,7.053,3.049,4.026,2.710,2.898
c2x-nets_3x3_imida_depth_lt_1,0.177,0.626,0.695,0.633,0.219,0.544,0.615,0.610,5.034,3.395,3.063,3.364,4.906,3.747,3.445,3.465
c2x-complex-nets_9x9_upct_depth_gt_1,-0.038,-3.028,-2.837,-2.008,0.003,0.120,0.501,0.475,3.761,7.409,7.232,6.403,3.687,3.463,2.608,2.675
c2x-nets_9x9_upct_depth_lt_1,0.234,0.568,0.673,0.605,0.280,0.626,0.694,0.679,3.679,2.763,2.405,2.641,3.566,2.572,2.326,2.383
c2x-complex-nets_9x9_imida_depth_lt_1,-0.019,-0.420,-0.366,-0.093,0.010,0.439,0.596,0.601,5.603,6.614,6.487,5.804,5.524,4.157,3.527,3.506
c2x-nets_5x5_upct_depth_lt_1,0.242,0.576,0.691,0.613,0.297,0.657,0.728,0.712,3.660,2.736,2.338,2.615,3.526,2.463,2.192,2.257
c2x-complex-nets_5x5_imida_depth_lt_1,-0.025,-0.486,-0.178,-0.058,-0.000,0.407,0.600,0.607,5.620,6.767,6.025,5.708,5.551,4.273,3.509,3.481
c2x-nets_9x9_upct_depth_gt_1,0.267,0.085,0.303,0.187,0.308,0.454,0.583,0.531,3.161,3.532,3.081,3.329,3.072,2.728,2.384,2.529